### ISSUE TITLE
Gzip

### ISSUE THREAD

**Issue by bennpearson** [ONSdigital/respondent-home-ui#16]
Check CSS and JS are gzipped

**Comment by johntopleyons** [comment]
CSS is being compressed, JavaScript isn't. Will add to backlog.

![rh-16](https://cloud.githubusercontent.com/assets/13464527/21936203/3bbbdcbc-d9a8-11e6-896f-ab2ca8f096e6.png)

**Comment by johntopleyons** [comment]
Added `application/javascript` to Apache gzip configuration.

![rh-js](https://cloud.githubusercontent.com/assets/13464527/21941078/fab2b7e2-d9be-11e6-9d47-4bc5c7fbddb7.png)
