### ISSUE TITLE
special characters

### ISSUE THREAD

**Issue by Chrs74uf** [ONSdigital/respondent-home-ui#2]
it's possible to enter special characters when JavaScript

<img width="1440" alt="special characters" src="https://cloud.githubusercontent.com/assets/24547196/21144294/01bf66ce-c142-11e6-83b4-68a1aa738332.png">

**Comment by johntopleyons** [comment]
Can you tell me who you are please?

**Comment by Chrs74uf** [comment]
Hi John, I am UX researcher working with EQ in Newport and in Tom Scott's
team in Tichfield.

Regards,
Chris

**Comment by johntopleyons** [comment]
Hi Chris. Not sure how you got that URL, but this is still in development and not for testing yet.

Regards,

John

**Comment by Chrs74uf** [comment]
ok. I won't comment again
Chris
