### ISSUE TITLE
entry field focus

### ISSUE THREAD

**Issue by Chrs74uf** [ONSdigital/respondent-home-ui#3]
Hijacking focus (IAC entry) may cause accessibility issues. Should test this with DAC?

**Comment by johntopleyons** [comment]
What's DAC?

**Comment by Chrs74uf** [comment]
Hi John,

DAC is 'the Digital Accessibility Centre' based in Swansea who help dev
teams with accessibility issues. (http://www.digitalaccessibilitycentre.org/
)
They are working with EQ to assess accessibility issues during the
design/build process,

 Chris

**Comment by johntopleyons** [comment]
Hi Chris,

Thanks, I didn't know that. I'll remove the auto-focus.

Cheers,

John
